version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: nest-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mailhog:
    image: mailhog/mailhog:latest
    container_name: nest-mailhog
    ports:
      - 1025:1025 
      - 8025:8025 # Web check mail

volumes:
  mongo-data: